//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>

// ------------------- Function Prototypes --------------------

void ____function_1f6b(int32_t a1);
void ___function_1edd(int32_t a1, int32_t a2);
void ___function_1f3c(int32_t a1);
void __function_1d0d(int32_t a1, int32_t a2);
void __function_1d8e(int32_t a1, int32_t a2);
void __function_1e6c(int32_t a1);
void __function_1ebd(int32_t a1);
void _function_17ed(int32_t a1, int32_t a2);
void _function_188e(int32_t a1, int32_t a2);
void _function_19bd(int32_t a1, int32_t a2);
void _function_1a2e(int32_t a1, int32_t a2);
void _function_1c5c(int32_t a1);
void _function_1cce(int32_t a1);
void _function_1d7c(int32_t a1);
void _function_1dde(int32_t a1);
void function_1a0d(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19);
void function_1ad1(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7);
void function_1c2d(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11);
void function_1ca1(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7);
void function_1ffd(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14);
void function_208e(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7);
void function_217d(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10);
void function_21f1(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6);
void function_272c(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13);
void function_27ae(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6);
void function_287c(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9);
void function_28de(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6);
void function_2a9c(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11);
void function_2b0e(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6);
void function_2bbc(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9);
void function_2c1e(char * a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // eax
int32_t g2 = 0; // ebp

// ------------------------ Functions -------------------------

// Address range: 0x1a00 - 0x1a0c
int main(int argc, char ** argv) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_1a0d(v2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
    return g1;
}

// Address range: 0x1a0d - 0x1abf
void function_1a0d(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14, int32_t a15, int32_t a16, int32_t a17, int32_t a18, int32_t a19) {
    int32_t v1 = g2; // 0x1a0e
    *(int32_t *)(v1 - 12) = 0;
    *(int32_t *)(g2 - 16) = *(int32_t *)(v1 + 8);
    *(int32_t *)(g2 - 20) = *(int32_t *)(v1 + 12);
    int32_t v2;
    *(int32_t *)(v2 + 0x1603) = v1 - 24;
    int32_t v3 = g2; // 0x1a2c
    *(int32_t *)(v3 - 32) = v2;
    *(int32_t *)(g2 - 36) = 0;
    _function_17ed(*(int32_t *)(v3 - 28), 0);
    g1 = *(int32_t *)(*(int32_t *)(g2 - 32) + 0x15ff);
}

// Address range: 0x1ac0 - 0x1ad0
void _function_17ed(int32_t a1, int32_t a2) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_1ad1(v2, 0, 0, 0, 0, 0, 0);
}

// Address range: 0x1ad1 - 0x1c1f
void function_1ad1(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7) {
    int32_t v1 = g2; // 0x1ad2
    int32_t v2;
    *(int32_t *)(v1 - 88) = v2;
    int32_t v3 = g2; // 0x1ae4
    *(int32_t *)(v3 - 92) = *(int32_t *)(v3 + 44);
    int32_t v4 = g2; // 0x1aea
    *(int32_t *)(v4 - 96) = *(int32_t *)(v4 + 40);
    int32_t v5 = g2; // 0x1af0
    *(int32_t *)(v5 - 100) = *(int32_t *)(v5 + 36);
    int32_t v6 = g2; // 0x1af6
    *(int32_t *)(v6 - 104) = *(int32_t *)(v6 + 32);
    int32_t v7 = g2; // 0x1afc
    *(int32_t *)(v7 - 108) = *(int32_t *)(v7 + 28);
    int32_t v8 = g2; // 0x1b02
    *(int32_t *)(v8 - 112) = *(int32_t *)(v8 + 24);
    int32_t v9 = g2; // 0x1b08
    *(int32_t *)(v9 - 116) = *(int32_t *)(v9 + 20);
    int32_t v10 = g2; // 0x1b0e
    *(int32_t *)(v10 - 120) = *(int32_t *)(v10 + 16);
    int32_t v11 = g2; // 0x1b14
    *(int32_t *)(v11 - 124) = *(int32_t *)(v11 + 12);
    int32_t v12 = g2; // 0x1b1a
    *(int32_t *)(v12 - 128) = *(int32_t *)(v12 + 8);
    *(int32_t *)(g2 - 132) = 0;
    int32_t v13 = g2; // 0x1b28
    *(int32_t *)(v13 - 16) = *(int32_t *)(v13 - 128);
    int32_t v14 = g2; // 0x1b2e
    *(int32_t *)(v14 - 20) = *(int32_t *)(v14 - 124);
    int32_t v15 = g2; // 0x1b34
    *(int32_t *)(v15 - 24) = *(int32_t *)(v15 - 120);
    int32_t v16 = g2; // 0x1b3a
    *(int32_t *)(v16 - 28) = *(int32_t *)(v16 - 116);
    int32_t v17 = g2; // 0x1b40
    *(int32_t *)(v17 - 32) = *(int32_t *)(v17 - 112);
    int32_t v18 = g2; // 0x1b46
    *(int32_t *)(v18 - 36) = *(int32_t *)(v18 - 108);
    int32_t v19 = g2; // 0x1b4c
    *(int32_t *)(v19 - 40) = *(int32_t *)(v19 - 104);
    int32_t v20 = g2; // 0x1b52
    *(int32_t *)(v20 - 44) = *(int32_t *)(v20 - 100);
    int32_t v21 = g2; // 0x1b58
    *(int32_t *)(v21 - 48) = *(int32_t *)(v21 - 96);
    int32_t v22 = g2; // 0x1b5e
    *(int32_t *)(v22 - 52) = *(int32_t *)(v22 - 92);
    *(int32_t *)(g2 - 56) = *(int32_t *)(v1 + 48);
    *(int32_t *)(g2 - 60) = *(int32_t *)(v1 + 52);
    *(int32_t *)(g2 - 64) = *(int32_t *)(v1 + 56);
    *(int32_t *)(g2 - 68) = *(int32_t *)(v1 + 60);
    *(int32_t *)(g2 - 72) = *(int32_t *)(v1 + 64);
    int32_t v23 = g2; // 0x1b73
    int32_t v24 = *(int32_t *)(v23 - 88); // 0x1b73
    *(int32_t *)(v23 - 76) = *(int32_t *)(v24 + 0x153f);
    *(int32_t *)(*(int32_t *)(g2 - 76) - 12) = 0;
    int32_t v25 = *(int32_t *)(*(int32_t *)(g2 - 76) + 8); // 0x1b8e
    *(int32_t *)(*(int32_t *)(v24 + 0x153f) - 16) = v25;
    int32_t v26 = *(int32_t *)(*(int32_t *)(g2 - 76) + 12); // 0x1b9f
    *(int32_t *)(*(int32_t *)(v24 + 0x153f) - 20) = v26;
    int32_t v27 = g2; // 0x1bad
    int32_t v28 = *(int32_t *)(v27 - 80); // 0x1bb3
    *(int32_t *)(v28 + 2083) = *(int32_t *)(v27 - 76) - 24;
    *(int32_t *)(g2 - 84) = *(int32_t *)(v24 + 0x153f);
    int32_t v29 = g2; // 0x1bc5
    *(int32_t *)(*(int32_t *)(v29 - 84) - 32) = *(int32_t *)(v29 - 80);
    *(int32_t *)(*(int32_t *)(v24 + 0x153f) - 36) = 0;
    __function_1d0d(*(int32_t *)(*(int32_t *)(g2 - 84) - 28), 0);
    int32_t v30 = *(int32_t *)(g2 - 88); // 0x1bf7
    int32_t v31 = *(int32_t *)(*(int32_t *)(*(int32_t *)(v30 + 0x153f) - 32) + 2079); // 0x1c05
    *(int32_t *)(v30 + 0x153b) = v31;
    int32_t v32;
    g2 = v32;
}

// Address range: 0x1c20 - 0x1c2c
void __function_1d0d(int32_t a1, int32_t a2) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_1c2d(v2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
}

// Address range: 0x1c2d - 0x1c8f
void function_1c2d(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11) {
    int32_t v1 = g2; // 0x1c2e
    *(int32_t *)(v1 - 12) = *(int32_t *)(v1 + 8);
    *(int32_t *)(g2 - 16) = *(int32_t *)(v1 + 12);
    int32_t v2;
    *(int32_t *)(v2 + 0x13e3) = v1 - 20;
    int32_t v3 = g2; // 0x1c45
    *(int32_t *)(v3 - 28) = 0;
    _function_188e(*(int32_t *)(v3 - 24), 0);
    int32_t v4;
    g2 = v4;
}

// Address range: 0x1c90 - 0x1ca0
void _function_188e(int32_t a1, int32_t a2) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_1ca1(v2, 0, 0, 0, 0, 0, 0);
}

// Address range: 0x1ca1 - 0x1fef
void function_1ca1(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7) {
    int32_t v1 = g2; // 0x1ca2
    int32_t v2;
    *(int32_t *)(v1 - 140) = v2;
    int32_t v3 = g2; // 0x1cb7
    *(int32_t *)(v3 - 144) = *(int32_t *)(v3 + 12);
    int32_t v4 = g2; // 0x1cc0
    *(int32_t *)(v4 - 148) = *(int32_t *)(v4 + 8);
    *(int32_t *)(g2 - 152) = 0;
    int32_t v5 = g2; // 0x1cd1
    *(int32_t *)(v5 - 16) = *(int32_t *)(v5 - 148);
    int32_t v6 = g2; // 0x1cda
    *(int32_t *)(v6 - 20) = *(int32_t *)(v6 - 144);
    *(int32_t *)(g2 - 24) = *(int32_t *)(v1 + 16);
    *(int32_t *)(g2 - 28) = *(int32_t *)(v1 + 20);
    *(int32_t *)(g2 - 32) = *(int32_t *)(v1 + 24);
    *(int32_t *)(g2 - 36) = *(int32_t *)(v1 + 28);
    *(int32_t *)(g2 - 40) = *(int32_t *)(v1 + 32);
    int32_t v7 = g2; // 0x1cf2
    int32_t v8 = *(int32_t *)(v7 - 140); // 0x1cf2
    *(int32_t *)(v7 - 44) = *(int32_t *)(v8 + 0x136f);
    int32_t v9 = g2; // 0x1d01
    *(int32_t *)(*(int32_t *)(v9 - 44) - 72) = *(int32_t *)(v9 - 48);
    *(int32_t *)(g2 - 52) = *(int32_t *)(v8 + 0x136f);
    int32_t v10 = *(int32_t *)(g2 - 52); // 0x1d15
    *(int32_t *)(v10 - 76) = *(int32_t *)(v10 + 28);
    *(int32_t *)(g2 - 56) = *(int32_t *)(v8 + 0x136f);
    int32_t v11 = *(int32_t *)(g2 - 56); // 0x1d2c
    *(int32_t *)(v11 - 80) = *(int32_t *)(v11 + 24);
    *(int32_t *)(g2 - 60) = *(int32_t *)(v8 + 0x136f);
    int32_t v12 = *(int32_t *)(g2 - 60); // 0x1d43
    *(int32_t *)(v12 - 84) = *(int32_t *)(v12 + 20);
    *(int32_t *)(g2 - 64) = *(int32_t *)(v8 + 0x136f);
    int32_t v13 = *(int32_t *)(g2 - 64); // 0x1d5a
    *(int32_t *)(v13 - 88) = *(int32_t *)(v13 + 16);
    *(int32_t *)(g2 - 68) = *(int32_t *)(v8 + 0x136f);
    int32_t v14 = *(int32_t *)(g2 - 68); // 0x1d71
    *(int32_t *)(v14 - 92) = *(int32_t *)(v14 + 12);
    *(int32_t *)(g2 - 72) = *(int32_t *)(v8 + 0x136f);
    int32_t v15 = *(int32_t *)(g2 - 72); // 0x1d88
    *(int32_t *)(v15 - 96) = *(int32_t *)(v15 + 8);
    *(int32_t *)(*(int32_t *)(v8 + 0x136f) - 100) = 0;
    *(int32_t *)(g2 - 76) = *(int32_t *)(v8 + 0x136f);
    int32_t v16 = *(int32_t *)(g2 - 76); // 0x1dae
    *(int32_t *)(v16 - 16) = *(int32_t *)(v16 - 96);
    *(int32_t *)(g2 - 80) = *(int32_t *)(v8 + 0x136f);
    int32_t v17 = *(int32_t *)(g2 - 80); // 0x1dc7
    *(int32_t *)(v17 - 20) = *(int32_t *)(v17 - 92);
    *(int32_t *)(g2 - 84) = *(int32_t *)(v8 + 0x136f);
    int32_t v18 = *(int32_t *)(g2 - 84); // 0x1de0
    *(int32_t *)(v18 - 24) = *(int32_t *)(v18 - 88);
    *(int32_t *)(g2 - 88) = *(int32_t *)(v8 + 0x136f);
    int32_t v19 = *(int32_t *)(g2 - 88); // 0x1df9
    *(int32_t *)(v19 - 28) = *(int32_t *)(v19 - 84);
    *(int32_t *)(g2 - 92) = *(int32_t *)(v8 + 0x136f);
    int32_t v20 = *(int32_t *)(g2 - 92); // 0x1e12
    *(int32_t *)(v20 - 32) = *(int32_t *)(v20 - 80);
    *(int32_t *)(g2 - 96) = *(int32_t *)(v8 + 0x136f);
    int32_t v21 = *(int32_t *)(g2 - 96); // 0x1e2b
    *(int32_t *)(v21 - 36) = *(int32_t *)(v21 - 76);
    int32_t v22 = *(int32_t *)(*(int32_t *)(g2 - 44) + 32); // 0x1e3e
    *(int32_t *)(*(int32_t *)(v8 + 0x136f) - 40) = v22;
    int32_t v23 = *(int32_t *)(*(int32_t *)(g2 - 44) + 36); // 0x1e4f
    *(int32_t *)(*(int32_t *)(v8 + 0x136f) - 44) = v23;
    int32_t v24 = *(int32_t *)(*(int32_t *)(g2 - 44) + 40); // 0x1e60
    *(int32_t *)(*(int32_t *)(v8 + 0x136f) - 48) = v24;
    int32_t v25 = *(int32_t *)(*(int32_t *)(g2 - 44) + 44); // 0x1e71
    *(int32_t *)(*(int32_t *)(v8 + 0x136f) - 52) = v25;
    int32_t v26 = *(int32_t *)(*(int32_t *)(g2 - 44) + 48); // 0x1e82
    *(int32_t *)(*(int32_t *)(v8 + 0x136f) - 56) = v26;
    *(int32_t *)(g2 - 100) = *(int32_t *)(v8 + 0x136f);
    int32_t v27 = g2; // 0x1e99
    *(int32_t *)(v27 - 104) = *(int32_t *)(*(int32_t *)(v27 - 100) - 72);
    int32_t v28 = g2; // 0x1ea4
    int32_t v29 = *(int32_t *)(v28 - 100); // 0x1ead
    *(int32_t *)(v29 - 60) = *(int32_t *)(*(int32_t *)(v28 - 104) + 1922);
    *(int32_t *)(*(int32_t *)(*(int32_t *)(v8 + 0x136f) - 60) - 12) = 0;
    int32_t v30 = *(int32_t *)(v8 + 0x136f); // 0x1ec9
    *(int32_t *)(g2 - 108) = *(int32_t *)(*(int32_t *)(v30 - 60) + 8);
    int32_t v31 = g2; // 0x1eda
    int32_t v32 = *(int32_t *)(v31 - 104); // 0x1edd
    *(int32_t *)(*(int32_t *)(v32 + 1922) - 16) = *(int32_t *)(v31 - 108);
    int32_t v33 = *(int32_t *)(v8 + 0x136f); // 0x1eeb
    *(int32_t *)(g2 - 112) = *(int32_t *)(*(int32_t *)(v33 - 60) + 12);
    int32_t v34 = g2; // 0x1efc
    int32_t v35 = *(int32_t *)(v34 - 104); // 0x1eff
    *(int32_t *)(*(int32_t *)(v35 + 1922) - 20) = *(int32_t *)(v34 - 112);
    *(int32_t *)(g2 - 116) = *(int32_t *)(v8 + 0x136f);
    int32_t v36 = g2; // 0x1f16
    *(int32_t *)(v36 - 120) = *(int32_t *)(*(int32_t *)(v36 - 116) - 64);
    int32_t v37 = g2; // 0x1f21
    int32_t v38 = *(int32_t *)(v37 - 116); // 0x1f21
    int32_t v39 = *(int32_t *)(v37 - 120); // 0x1f2c
    *(int32_t *)(v39 + 771) = *(int32_t *)(v38 - 60) - 24;
    int32_t v40 = *(int32_t *)(v8 + 0x136f); // 0x1f3e
    *(int32_t *)(v40 - 68) = *(int32_t *)(*(int32_t *)(g2 - 104) + 1922);
    *(int32_t *)(g2 - 124) = *(int32_t *)(v8 + 0x136f);
    int32_t v41 = *(int32_t *)(g2 - 124); // 0x1f52
    *(int32_t *)(*(int32_t *)(v41 - 68) - 32) = *(int32_t *)(v41 - 64);
    *(int32_t *)(*(int32_t *)(*(int32_t *)(g2 - 104) + 1922) - 36) = 0;
    int32_t v42 = *(int32_t *)(v8 + 0x136f); // 0x1f79
    ___function_1edd(*(int32_t *)(*(int32_t *)(v42 - 68) - 28), 0);
    int32_t v43 = *(int32_t *)(g2 - 140); // 0x1f99
    *(int32_t *)(g2 - 128) = *(int32_t *)(*(int32_t *)(v43 + 0x136f) - 72);
    int32_t v44 = *(int32_t *)(*(int32_t *)(g2 - 128) + 1922); // 0x1fb0
    *(int32_t *)(g2 - 132) = *(int32_t *)(*(int32_t *)(v44 - 32) + 767);
    *(int32_t *)(*(int32_t *)(g2 - 128) + 1918) = *(int32_t *)(g2 - 132);
    *(int32_t *)(v43 + 0x136f) = *(int32_t *)(g2 - 136);
}

// Address range: 0x1ff0 - 0x1ffc
void ___function_1edd(int32_t a1, int32_t a2) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_1ffd(v2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
}

// Address range: 0x1ffd - 0x207f
void function_1ffd(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13, int32_t a14) {
    int32_t v1 = g2; // 0x1ffe
    *(int32_t *)(v1 - 12) = *(int32_t *)(v1 + 8);
    *(int32_t *)(g2 - 16) = *(int32_t *)(v1 + 12);
    int32_t v2;
    *(int32_t *)(v2 + 0x1013) = v1 - 20;
    int32_t v3 = g2; // 0x2015
    *(int32_t *)(v3 - 28) = 0;
    _function_19bd(*(int32_t *)(v3 - 24), 0);
    int32_t v4;
    g2 = v4;
}

// Address range: 0x2080 - 0x208d
void _function_19bd(int32_t a1, int32_t a2) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_208e(v2, 0, 0, 0, 0, 0, 0);
}

// Address range: 0x208e - 0x216f
void function_208e(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7) {
    int32_t v1 = g2; // 0x208f
    int32_t v2;
    *(int32_t *)(v1 - 72) = v2;
    int32_t v3 = g2; // 0x20a1
    *(int32_t *)(v3 - 76) = *(int32_t *)(v3 + 24);
    int32_t v4 = g2; // 0x20a7
    *(int32_t *)(v4 - 80) = *(int32_t *)(v4 + 20);
    int32_t v5 = g2; // 0x20ad
    *(int32_t *)(v5 - 84) = *(int32_t *)(v5 + 16);
    int32_t v6 = g2; // 0x20b3
    *(int32_t *)(v6 - 88) = *(int32_t *)(v6 + 12);
    int32_t v7 = g2; // 0x20b9
    *(int32_t *)(v7 - 92) = *(int32_t *)(v7 + 8);
    *(int32_t *)(g2 - 96) = 0;
    int32_t v8 = g2; // 0x20c4
    *(int32_t *)(v8 - 16) = *(int32_t *)(v8 - 92);
    int32_t v9 = g2; // 0x20ca
    *(int32_t *)(v9 - 20) = *(int32_t *)(v9 - 88);
    int32_t v10 = g2; // 0x20d0
    *(int32_t *)(v10 - 24) = *(int32_t *)(v10 - 84);
    int32_t v11 = g2; // 0x20d6
    *(int32_t *)(v11 - 28) = *(int32_t *)(v11 - 80);
    int32_t v12 = g2; // 0x20dc
    *(int32_t *)(v12 - 32) = *(int32_t *)(v12 - 76);
    *(int32_t *)(g2 - 36) = *(int32_t *)(v1 + 28);
    *(int32_t *)(g2 - 40) = *(int32_t *)(v1 + 32);
    *(int32_t *)(g2 - 44) = *(int32_t *)(v1 + 36);
    *(int32_t *)(g2 - 48) = *(int32_t *)(v1 + 40);
    *(int32_t *)(g2 - 52) = *(int32_t *)(v1 + 44);
    int32_t v13 = g2; // 0x20f1
    int32_t v14 = *(int32_t *)(v13 - 72); // 0x20f1
    *(int32_t *)(v13 - 56) = *(int32_t *)(v14 + 3970);
    int32_t v15 = *(int32_t *)(g2 - 56); // 0x20fd
    *(int32_t *)(v15 - 12) = *(int32_t *)(v15 + 8);
    int32_t v16 = *(int32_t *)(*(int32_t *)(g2 - 56) + 12); // 0x210e
    *(int32_t *)(*(int32_t *)(v14 + 3970) - 16) = v16;
    int32_t v17 = g2; // 0x211c
    int32_t v18 = *(int32_t *)(v17 - 60); // 0x2122
    *(int32_t *)(v18 + 1619) = *(int32_t *)(v17 - 56) - 20;
    *(int32_t *)(g2 - 64) = *(int32_t *)(v14 + 3970);
    *(int32_t *)(*(int32_t *)(g2 - 64) - 28) = 0;
    __function_1d8e(*(int32_t *)(*(int32_t *)(g2 - 64) - 24), 0);
    *(int32_t *)(*(int32_t *)(g2 - 72) + 3970) = *(int32_t *)(g2 - 68);
}

// Address range: 0x2170 - 0x217c
void __function_1d8e(int32_t a1, int32_t a2) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_217d(v2, 0, 0, 0, 0, 0, 0, 0, 0, 0);
}

// Address range: 0x217d - 0x21df
void function_217d(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10) {
    int32_t v1 = g2; // 0x217e
    *(int32_t *)(v1 - 12) = *(int32_t *)(v1 + 8);
    *(int32_t *)(g2 - 16) = *(int32_t *)(v1 + 12);
    int32_t v2;
    *(int32_t *)(v2 + 3731) = v1 - 20;
    int32_t v3 = g2; // 0x2195
    *(int32_t *)(v3 - 28) = 0;
    _function_1a2e(*(int32_t *)(v3 - 24), 0);
    int32_t v4;
    g2 = v4;
}

// Address range: 0x21e0 - 0x21f0
void _function_1a2e(int32_t a1, int32_t a2) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_21f1(v2, 0, 0, 0, 0, 0);
}

// Address range: 0x21f1 - 0x271f
void function_21f1(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6) {
    int32_t v1 = g2; // 0x21f2
    int32_t v2;
    *(int32_t *)(v1 - 172) = v2;
    int32_t v3 = g2; // 0x2207
    *(int32_t *)(v3 - 16) = *(int32_t *)(v3 + 8);
    *(int32_t *)(g2 - 20) = *(int32_t *)(v1 + 12);
    *(int32_t *)(g2 - 24) = *(int32_t *)(v1 + 16);
    *(int32_t *)(g2 - 28) = *(int32_t *)(v1 + 20);
    *(int32_t *)(g2 - 32) = *(int32_t *)(v1 + 24);
    *(int32_t *)(g2 - 36) = *(int32_t *)(v1 + 28);
    int32_t v4 = g2; // 0x221c
    int32_t v5 = *(int32_t *)(v4 - 172); // 0x221c
    int32_t v6 = v5; // eax
    *(int32_t *)(v4 - 40) = *(int32_t *)(v5 + 3615);
    int32_t v7 = g2; // 0x222b
    *(int32_t *)(*(int32_t *)(v7 - 40) - 100) = *(int32_t *)(v7 - 44);
    *(int32_t *)(g2 - 48) = *(int32_t *)(v6 + 3615);
    int32_t * v8 = (int32_t *)(g2 - 48); // 0x223f_0
    *(int32_t *)(*v8 - 16) = *(int32_t *)(*v8 + 8);
    int32_t v9 = *(int32_t *)(*(int32_t *)(g2 - 40) + 12); // 0x2250
    *(int32_t *)(*(int32_t *)(v6 + 3615) - 20) = v9;
    int32_t v10 = *(int32_t *)(*(int32_t *)(g2 - 40) + 16); // 0x2261
    *(int32_t *)(*(int32_t *)(v6 + 3615) - 24) = v10;
    int32_t v11 = *(int32_t *)(*(int32_t *)(g2 - 40) + 20); // 0x2272
    *(int32_t *)(*(int32_t *)(v6 + 3615) - 28) = v11;
    int32_t v12 = *(int32_t *)(*(int32_t *)(g2 - 40) + 24); // 0x2283
    *(int32_t *)(*(int32_t *)(v6 + 3615) - 32) = v12;
    int32_t v13 = *(int32_t *)(*(int32_t *)(g2 - 40) + 28); // 0x2294
    *(int32_t *)(*(int32_t *)(v6 + 3615) - 36) = v13;
    *(int32_t *)(g2 - 52) = *(int32_t *)(v6 + 3615);
    int32_t v14 = g2; // 0x22ab
    *(int32_t *)(v14 - 56) = *(int32_t *)(*(int32_t *)(v14 - 52) - 100);
    int32_t v15 = g2; // 0x22b6
    int32_t v16 = *(int32_t *)(v15 - 52); // 0x22bf
    *(int32_t *)(v16 - 40) = *(int32_t *)(*(int32_t *)(v15 - 56) + 1506);
    *(int32_t *)(g2 - 60) = *(int32_t *)(v6 + 3615);
    int32_t * v17 = (int32_t *)(g2 - 60); // 0x22d0_0
    int32_t v18 = *(int32_t *)(*v17 - 40); // 0x22de
    *(int32_t *)(v18 - 56) = *(int32_t *)(*v17 - 44);
    int32_t v19 = *(int32_t *)(v6 + 3615); // 0x22ee
    *(int32_t *)(v19 - 48) = *(int32_t *)(*(int32_t *)(g2 - 56) + 1506);
    *(int32_t *)(g2 - 64) = *(int32_t *)(v6 + 3615) - 48;
    int32_t * v20 = (int32_t *)(g2 - 64); // 0x2305_0
    int32_t v21 = *(int32_t *)(*(int32_t *)*v20 + 12); // 0x230a
    *(int32_t *)(*(int32_t *)*v20 - 60) = v21;
    int32_t v22 = *(int32_t *)(v6 + 3615); // 0x2320
    *(int32_t *)(v22 - 52) = *(int32_t *)(*(int32_t *)(g2 - 56) + 1506);
    *(int32_t *)(g2 - 68) = *(int32_t *)(v6 + 3615) - 52;
    int32_t * v23 = (int32_t *)(g2 - 68); // 0x2337_0
    int32_t v24 = *(int32_t *)(*(int32_t *)*v23 + 8); // 0x233c
    *(int32_t *)(*(int32_t *)*v23 - 16) = v24;
    int32_t v25 = *(int32_t *)(v6 + 3615); // 0x2352
    *(int32_t *)(v25 - 56) = *(int32_t *)(*(int32_t *)(g2 - 56) + 1506);
    *(int32_t *)(g2 - 72) = *(int32_t *)(v6 + 3615) - 56;
    int32_t * v26 = (int32_t *)(g2 - 72); // 0x2369_0
    int32_t v27 = *(int32_t *)(*(int32_t *)*v26 - 60); // 0x2371
    *(int32_t *)(*(int32_t *)*v26 - 20) = v27;
    int32_t v28 = *(int32_t *)(v6 + 3615); // 0x237d
    *(int32_t *)(g2 - 76) = *(int32_t *)(*(int32_t *)(v28 - 40) + 16);
    int32_t v29 = g2; // 0x238e
    int32_t v30 = *(int32_t *)(v29 - 56); // 0x2391
    *(int32_t *)(*(int32_t *)(v30 + 1506) - 24) = *(int32_t *)(v29 - 76);
    int32_t v31 = *(int32_t *)(v6 + 3615); // 0x239f
    *(int32_t *)(g2 - 80) = *(int32_t *)(*(int32_t *)(v31 - 40) + 20);
    int32_t v32 = g2; // 0x23b0
    int32_t v33 = *(int32_t *)(v32 - 56); // 0x23b3
    *(int32_t *)(*(int32_t *)(v33 + 1506) - 28) = *(int32_t *)(v32 - 80);
    int32_t v34 = *(int32_t *)(v6 + 3615); // 0x23c1
    *(int32_t *)(g2 - 84) = *(int32_t *)(*(int32_t *)(v34 - 40) + 24);
    int32_t v35 = g2; // 0x23d2
    int32_t v36 = *(int32_t *)(v35 - 56); // 0x23d5
    *(int32_t *)(*(int32_t *)(v36 + 1506) - 32) = *(int32_t *)(v35 - 84);
    int32_t v37 = *(int32_t *)(v6 + 3615); // 0x23e3
    *(int32_t *)(g2 - 88) = *(int32_t *)(*(int32_t *)(v37 - 40) + 28);
    int32_t v38 = g2; // 0x23f4
    int32_t v39 = *(int32_t *)(v38 - 56); // 0x23f7
    *(int32_t *)(*(int32_t *)(v39 + 1506) - 36) = *(int32_t *)(v38 - 88);
    int32_t v40 = *(int32_t *)(v6 + 3615); // 0x2405
    *(int32_t *)(g2 - 92) = *(int32_t *)(*(int32_t *)(v40 - 40) + 32);
    int32_t v41 = g2; // 0x2416
    int32_t v42 = *(int32_t *)(v41 - 56); // 0x2419
    *(int32_t *)(*(int32_t *)(v42 + 1506) - 40) = *(int32_t *)(v41 - 92);
    int32_t v43 = *(int32_t *)(v6 + 3615); // 0x2430
    *(int32_t *)(v43 - 60) = *(int32_t *)(*(int32_t *)(g2 - 56) + 1506);
    *(int32_t *)(g2 - 96) = *(int32_t *)(v6 + 3615);
    int32_t * v44 = (int32_t *)(g2 - 96); // 0x2444_0
    int32_t v45 = *(int32_t *)(*(int32_t *)(*v44 - 60) - 56); // 0x244f
    *(int32_t *)(*v44 - 64) = v45;
    *(int32_t *)(g2 - 100) = *(int32_t *)(v6 + 3615);
    int32_t v46 = g2; // 0x2462
    *(int32_t *)(v46 - 104) = *(int32_t *)(*(int32_t *)(v46 - 100) - 60);
    int32_t v47 = g2; // 0x246d
    int32_t v48 = *(int32_t *)(*(int32_t *)(*(int32_t *)(v47 - 100) - 64) + 642); // 0x2475
    *(int32_t *)(*(int32_t *)(v47 - 104) - 44) = v48;
    int32_t v49 = *(int32_t *)(g2 - 56); // 0x2483
    *(int32_t *)(*(int32_t *)(*(int32_t *)(v49 + 1506) - 44) - 12) = 0;
    int32_t v50 = g2; // 0x249a
    *(int32_t *)(v50 - 108) = *(int32_t *)(*(int32_t *)(v50 - 56) + 1506);
    int32_t v51 = *(int32_t *)(*(int32_t *)(*(int32_t *)(g2 - 108) - 44) + 8); // 0x24ae
    *(int32_t *)(*(int32_t *)(v6 + 3615) - 68) = v51;
    *(int32_t *)(g2 - 112) = *(int32_t *)(v6 + 3615);
    int32_t v52 = g2; // 0x24c5
    *(int32_t *)(v52 - 116) = *(int32_t *)(*(int32_t *)(v52 - 112) - 64);
    int32_t v53 = g2; // 0x24d0
    int32_t v54 = *(int32_t *)(*(int32_t *)(v53 - 116) + 642); // 0x24db
    *(int32_t *)(v54 - 16) = *(int32_t *)(*(int32_t *)(v53 - 112) - 68);
    int32_t v55 = g2; // 0x24e6
    *(int32_t *)(v55 - 120) = *(int32_t *)(*(int32_t *)(v55 - 56) + 1506);
    int32_t v56 = *(int32_t *)(*(int32_t *)(*(int32_t *)(g2 - 120) - 44) + 12); // 0x24fa
    *(int32_t *)(*(int32_t *)(v6 + 3615) - 72) = v56;
    *(int32_t *)(g2 - 124) = *(int32_t *)(v6 + 3615);
    int32_t v57 = g2; // 0x2511
    *(int32_t *)(v57 - 128) = *(int32_t *)(*(int32_t *)(v57 - 124) - 64);
    int32_t v58 = g2; // 0x251c
    int32_t v59 = *(int32_t *)(*(int32_t *)(v58 - 128) + 642); // 0x2527
    *(int32_t *)(v59 - 20) = *(int32_t *)(*(int32_t *)(v58 - 124) - 72);
    int32_t v60 = *(int32_t *)(v6 + 3615); // 0x253b
    *(int32_t *)(v60 - 76) = *(int32_t *)(*(int32_t *)(g2 - 56) + 1506);
    *(int32_t *)(g2 - 132) = *(int32_t *)(v6 + 3615);
    int32_t * v61 = (int32_t *)(g2 - 132); // 0x2552_0
    int32_t v62 = *(int32_t *)(*(int32_t *)(*v61 - 76) - 48); // 0x2560
    *(int32_t *)(*v61 - 80) = v62;
    *(int32_t *)(g2 - 136) = *(int32_t *)(v6 + 3615);
    int32_t v63 = g2; // 0x2579
    *(int32_t *)(v63 - 140) = *(int32_t *)(*(int32_t *)(v63 - 136) - 76);
    int32_t v64 = g2; // 0x258a
    *(int32_t *)(v64 - 144) = *(int32_t *)(*(int32_t *)(v64 - 136) - 80);
    int32_t v65 = g2; // 0x259b
    int32_t v66 = *(int32_t *)(v65 - 140); // 0x259b
    int32_t v67 = *(int32_t *)(v65 - 144); // 0x25a9
    *(int32_t *)(v67 + 307) = *(int32_t *)(v66 - 44) - 24;
    int32_t v68 = g2; // 0x25b5
    *(int32_t *)(v68 - 148) = *(int32_t *)(*(int32_t *)(v68 - 56) + 1506);
    int32_t v69 = *(int32_t *)(v6 + 3615); // 0x25c4
    int32_t v70 = *(int32_t *)(g2 - 148); // 0x25d5
    *(int32_t *)(v70 - 52) = *(int32_t *)(*(int32_t *)(v69 - 64) + 642);
    int32_t v71 = *(int32_t *)(v6 + 3615); // 0x25e9
    *(int32_t *)(v71 - 84) = *(int32_t *)(*(int32_t *)(g2 - 56) + 1506);
    *(int32_t *)(g2 - 152) = *(int32_t *)(v6 + 3615) - 84;
    int32_t v72 = g2; // 0x2603
    int32_t v73 = *(int32_t *)(v72 - 152); // 0x2603
    *(int32_t *)(v72 - 156) = *(int32_t *)(*(int32_t *)v73 - 52);
    int32_t v74 = g2; // 0x2616
    int32_t v75 = *(int32_t *)(*(int32_t *)*(int32_t *)(v74 - 152) - 48); // 0x2621
    *(int32_t *)(*(int32_t *)(v74 - 156) - 32) = v75;
    int32_t v76 = *(int32_t *)(v6 + 3615); // 0x262e
    *(int32_t *)(*(int32_t *)(*(int32_t *)(v76 - 64) + 642) - 36) = 0;
    int32_t v77 = g2; // 0x2648
    *(int32_t *)(v77 - 160) = *(int32_t *)(*(int32_t *)(v77 - 56) + 1506);
    int32_t v78 = *(int32_t *)(g2 - 160); // 0x2657
    ____function_1f6b(*(int32_t *)(*(int32_t *)(v78 - 52) - 28));
    int32_t v79 = *(int32_t *)(g2 - 172); // 0x266f
    v6 = v79;
    *(int32_t *)(g2 - 164) = *(int32_t *)(*(int32_t *)(v79 + 3615) - 100);
    int32_t v80 = *(int32_t *)(*(int32_t *)(g2 - 164) + 1506); // 0x268c
    int32_t v81 = *(int32_t *)(v6 + 3615); // 0x2697
    *(int32_t *)(v81 - 88) = *(int32_t *)(v80 - 56);
    int32_t v82 = *(int32_t *)(v6 + 3615); // 0x26a2
    *(int32_t *)(g2 - 168) = *(int32_t *)(*(int32_t *)(v82 - 88) + 642);
    int32_t v83 = *(int32_t *)(*(int32_t *)(*(int32_t *)(g2 - 168) - 32) + 303); // 0x26c4
    *(int32_t *)(*(int32_t *)(v6 + 3615) - 92) = v83;
    int32_t * v84 = (int32_t *)(v6 + 3615); // 0x26d5_0
    int32_t v85 = *(int32_t *)(*v84 - 88); // 0x26e9
    *(int32_t *)(v85 + 638) = *(int32_t *)(*v84 - 92);
    int32_t v86 = *(int32_t *)(v6 + 3615); // 0x26f1
    *(int32_t *)(*(int32_t *)(g2 - 164) + 1506) = *(int32_t *)(v86 - 96);
}

// Address range: 0x2720 - 0x272b
void ____function_1f6b(int32_t a1) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_272c(v2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
}

// Address range: 0x272c - 0x279f
void function_272c(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11, int32_t a12, int32_t a13) {
    int32_t v1 = g2; // 0x272d
    *(int32_t *)(v1 - 8) = *(int32_t *)(v1 + 8);
    int32_t v2;
    *(int32_t *)(v2 + 2276) = v1 - 12;
    int32_t v3 = g2; // 0x273e
    *(int32_t *)(v3 - 20) = 0;
    _function_1c5c(*(int32_t *)(v3 - 16));
    int32_t v4;
    g2 = v4;
}

// Address range: 0x27a0 - 0x27ad
void _function_1c5c(int32_t a1) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_27ae(v2, 0, 0, 0, 0, 0);
}

// Address range: 0x27ae - 0x286f
void function_27ae(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6) {
    int32_t v1 = g2; // 0x27af
    int32_t v2;
    *(int32_t *)(v1 - 72) = v2;
    int32_t v3 = g2; // 0x27c1
    *(int32_t *)(v3 - 76) = *(int32_t *)(v3 + 24);
    int32_t v4 = g2; // 0x27c7
    *(int32_t *)(v4 - 80) = *(int32_t *)(v4 + 20);
    int32_t v5 = g2; // 0x27cd
    *(int32_t *)(v5 - 84) = *(int32_t *)(v5 + 16);
    int32_t v6 = g2; // 0x27d3
    *(int32_t *)(v6 - 88) = *(int32_t *)(v6 + 12);
    int32_t v7 = g2; // 0x27d9
    *(int32_t *)(v7 - 16) = *(int32_t *)(v7 + 8);
    int32_t v8 = g2; // 0x27df
    *(int32_t *)(v8 - 20) = *(int32_t *)(v8 - 88);
    int32_t v9 = g2; // 0x27e5
    *(int32_t *)(v9 - 24) = *(int32_t *)(v9 - 84);
    int32_t v10 = g2; // 0x27eb
    *(int32_t *)(v10 - 28) = *(int32_t *)(v10 - 80);
    int32_t v11 = g2; // 0x27f1
    *(int32_t *)(v11 - 32) = *(int32_t *)(v11 - 76);
    *(int32_t *)(g2 - 36) = *(int32_t *)(v1 + 28);
    *(int32_t *)(g2 - 40) = *(int32_t *)(v1 + 32);
    *(int32_t *)(g2 - 44) = *(int32_t *)(v1 + 36);
    *(int32_t *)(g2 - 48) = *(int32_t *)(v1 + 40);
    *(int32_t *)(g2 - 52) = *(int32_t *)(v1 + 44);
    int32_t v12 = g2; // 0x2806
    int32_t v13 = *(int32_t *)(v12 - 72); // 0x2806
    *(int32_t *)(v12 - 56) = *(int32_t *)(v13 + 2146);
    int32_t v14 = *(int32_t *)(g2 - 56); // 0x2812
    *(int32_t *)(v14 - 8) = *(int32_t *)(v14 + 8);
    int32_t v15 = g2; // 0x2820
    int32_t v16 = *(int32_t *)(v15 - 60); // 0x2826
    *(int32_t *)(v16 + 948) = *(int32_t *)(v15 - 56) - 12;
    *(int32_t *)(g2 - 64) = *(int32_t *)(v13 + 2146);
    *(int32_t *)(*(int32_t *)(g2 - 64) - 20) = 0;
    __function_1e6c(*(int32_t *)(*(int32_t *)(g2 - 64) - 16));
    *(int32_t *)(*(int32_t *)(g2 - 72) + 2146) = *(int32_t *)(g2 - 68);
}

// Address range: 0x2870 - 0x287b
void __function_1e6c(int32_t a1) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_287c(v2, 0, 0, 0, 0, 0, 0, 0, 0);
}

// Address range: 0x287c - 0x28cf
void function_287c(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9) {
    int32_t v1 = g2; // 0x287d
    *(int32_t *)(v1 - 8) = *(int32_t *)(v1 + 8);
    int32_t v2;
    *(int32_t *)(v2 + 1940) = v1 - 12;
    int32_t v3 = g2; // 0x288e
    *(int32_t *)(v3 - 20) = 0;
    _function_1cce(*(int32_t *)(v3 - 16));
    int32_t v4;
    g2 = v4;
}

// Address range: 0x28d0 - 0x28dd
void _function_1cce(int32_t a1) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_28de(v2, 0, 0, 0, 0, 0);
}

// Address range: 0x28de - 0x2a8f
void function_28de(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6) {
    int32_t v1 = g2; // 0x28df
    int32_t v2;
    *(int32_t *)(v1 - 80) = v2;
    int32_t v3 = g2; // 0x28f1
    *(int32_t *)(v3 - 16) = *(int32_t *)(v3 + 8);
    *(int32_t *)(g2 - 20) = *(int32_t *)(v1 + 12);
    *(int32_t *)(g2 - 24) = *(int32_t *)(v1 + 16);
    *(int32_t *)(g2 - 28) = *(int32_t *)(v1 + 20);
    *(int32_t *)(g2 - 32) = *(int32_t *)(v1 + 24);
    *(int32_t *)(g2 - 36) = *(int32_t *)(v1 + 28);
    int32_t v4 = g2; // 0x2906
    int32_t v5 = *(int32_t *)(v4 - 80); // 0x2906
    *(int32_t *)(v4 - 40) = *(int32_t *)(v5 + 1842);
    int32_t v6 = g2; // 0x2912
    *(int32_t *)(*(int32_t *)(v6 - 40) - 60) = *(int32_t *)(v6 - 44);
    *(int32_t *)(g2 - 48) = *(int32_t *)(v5 + 1842);
    int32_t * v7 = (int32_t *)(g2 - 48); // 0x2926_0
    *(int32_t *)(*v7 - 64) = *(int32_t *)(*v7 + 12);
    *(int32_t *)(g2 - 52) = *(int32_t *)(v5 + 1842);
    int32_t * v8 = (int32_t *)(g2 - 52); // 0x293d_0
    *(int32_t *)(*v8 - 16) = *(int32_t *)(*v8 + 8);
    *(int32_t *)(g2 - 56) = *(int32_t *)(v5 + 1842);
    int32_t * v9 = (int32_t *)(g2 - 56); // 0x2954_0
    *(int32_t *)(*v9 - 20) = *(int32_t *)(*v9 - 64);
    int32_t v10 = *(int32_t *)(*(int32_t *)(g2 - 40) + 16); // 0x2967
    *(int32_t *)(*(int32_t *)(v5 + 1842) - 24) = v10;
    int32_t v11 = *(int32_t *)(*(int32_t *)(g2 - 40) + 20); // 0x2978
    *(int32_t *)(*(int32_t *)(v5 + 1842) - 28) = v11;
    int32_t v12 = *(int32_t *)(*(int32_t *)(g2 - 40) + 24); // 0x2989
    *(int32_t *)(*(int32_t *)(v5 + 1842) - 32) = v12;
    int32_t v13 = *(int32_t *)(*(int32_t *)(g2 - 40) + 28); // 0x299a
    *(int32_t *)(*(int32_t *)(v5 + 1842) - 36) = v13;
    int32_t v14 = *(int32_t *)(*(int32_t *)(g2 - 40) + 32); // 0x29ab
    *(int32_t *)(*(int32_t *)(v5 + 1842) - 40) = v14;
    *(int32_t *)(g2 - 60) = *(int32_t *)(v5 + 1842);
    int32_t v15 = g2; // 0x29c2
    *(int32_t *)(v15 - 64) = *(int32_t *)(*(int32_t *)(v15 - 60) - 60);
    int32_t v16 = g2; // 0x29cd
    int32_t v17 = *(int32_t *)(v16 - 60); // 0x29d6
    *(int32_t *)(v17 - 44) = *(int32_t *)(*(int32_t *)(v16 - 64) + 834);
    *(int32_t *)(g2 - 68) = *(int32_t *)(*(int32_t *)(v5 + 1842) - 44);
    int32_t * v18 = (int32_t *)(g2 - 68); // 0x29ec_0
    *(int32_t *)(*v18 - 8) = *(int32_t *)(*v18 + 8);
    *(int32_t *)(g2 - 72) = *(int32_t *)(v5 + 1842);
    int32_t v19 = g2; // 0x2a03
    *(int32_t *)(v19 - 76) = *(int32_t *)(*(int32_t *)(v19 - 72) - 48);
    int32_t v20 = g2; // 0x2a0e
    int32_t v21 = *(int32_t *)(v20 - 72); // 0x2a0e
    int32_t v22 = *(int32_t *)(v20 - 76); // 0x2a19
    *(int32_t *)(v22 + 420) = *(int32_t *)(v21 - 44) - 12;
    int32_t v23 = *(int32_t *)(v5 + 1842); // 0x2a2b
    *(int32_t *)(v23 - 52) = *(int32_t *)(*(int32_t *)(g2 - 64) + 834);
    *(int32_t *)(*(int32_t *)(*(int32_t *)(v5 + 1842) - 52) - 20) = 0;
    int32_t v24 = *(int32_t *)(v5 + 1842); // 0x2a4a
    ___function_1f3c(*(int32_t *)(*(int32_t *)(v24 - 52) - 16));
    int32_t * v25 = (int32_t *)(*(int32_t *)(g2 - 80) + 1842); // 0x2a65_0
    int32_t v26 = *(int32_t *)(*v25 - 60); // 0x2a79
    *(int32_t *)(v26 + 834) = *(int32_t *)(*v25 - 56);
}

// Address range: 0x2a90 - 0x2a9b
void ___function_1f3c(int32_t a1) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_2a9c(v2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
}

// Address range: 0x2a9c - 0x2aff
void function_2a9c(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11) {
    int32_t v1 = g2; // 0x2a9d
    *(int32_t *)(v1 - 8) = *(int32_t *)(v1 + 8);
    int32_t v2;
    *(int32_t *)(v2 + 1396) = v1 - 12;
    int32_t v3 = g2; // 0x2aae
    *(int32_t *)(v3 - 20) = 0;
    _function_1d7c(*(int32_t *)(v3 - 16));
    int32_t v4;
    g2 = v4;
}

// Address range: 0x2b00 - 0x2b0d
void _function_1d7c(int32_t a1) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_2b0e(v2, 0, 0, 0, 0, 0);
}

// Address range: 0x2b0e - 0x2baf
void function_2b0e(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6) {
    int32_t v1 = g2; // 0x2b0f
    int32_t v2;
    *(int32_t *)(v1 - 64) = v2;
    int32_t v3 = g2; // 0x2b21
    *(int32_t *)(v3 - 68) = *(int32_t *)(v3 + 16);
    int32_t v4 = g2; // 0x2b27
    *(int32_t *)(v4 - 72) = *(int32_t *)(v4 + 12);
    int32_t v5 = g2; // 0x2b2d
    *(int32_t *)(v5 - 16) = *(int32_t *)(v5 + 8);
    int32_t v6 = g2; // 0x2b33
    *(int32_t *)(v6 - 20) = *(int32_t *)(v6 - 72);
    int32_t v7 = g2; // 0x2b39
    *(int32_t *)(v7 - 24) = *(int32_t *)(v7 - 68);
    *(int32_t *)(g2 - 28) = *(int32_t *)(v1 + 20);
    *(int32_t *)(g2 - 32) = *(int32_t *)(v1 + 24);
    *(int32_t *)(g2 - 36) = *(int32_t *)(v1 + 28);
    *(int32_t *)(g2 - 40) = *(int32_t *)(v1 + 32);
    *(int32_t *)(g2 - 44) = *(int32_t *)(v1 + 36);
    int32_t v8 = g2; // 0x2b4e
    int32_t v9 = *(int32_t *)(v8 - 64); // 0x2b4e
    *(int32_t *)(v8 - 48) = *(int32_t *)(v9 + 1282);
    int32_t v10 = *(int32_t *)(g2 - 48); // 0x2b5a
    *(int32_t *)(v10 - 8) = *(int32_t *)(v10 + 8);
    int32_t v11 = g2; // 0x2b68
    int32_t v12 = *(int32_t *)(v11 - 52); // 0x2b6e
    *(int32_t *)(v12 + 660) = *(int32_t *)(v11 - 48) - 12;
    *(int32_t *)(g2 - 56) = *(int32_t *)(v9 + 1282);
    *(int32_t *)(*(int32_t *)(g2 - 56) - 20) = 0;
    __function_1ebd(*(int32_t *)(*(int32_t *)(g2 - 56) - 16));
    *(int32_t *)(*(int32_t *)(g2 - 64) + 1282) = *(int32_t *)(g2 - 60);
}

// Address range: 0x2bb0 - 0x2bbb
void __function_1ebd(int32_t a1) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_2bbc(v2, 0, 0, 0, 0, 0, 0, 0, 0);
}

// Address range: 0x2bbc - 0x2c0f
void function_2bbc(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9) {
    int32_t v1 = g2; // 0x2bbd
    *(int32_t *)(v1 - 8) = *(int32_t *)(v1 + 8);
    int32_t v2;
    *(int32_t *)(v2 + 1108) = v1 - 12;
    int32_t v3 = g2; // 0x2bce
    *(int32_t *)(v3 - 20) = 0;
    _function_1dde(*(int32_t *)(v3 - 16));
    int32_t v4;
    g2 = v4;
}

// Address range: 0x2c10 - 0x2c1d
void _function_1dde(int32_t a1) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_2c1e((char *)v2, 0, 0, 0, 0, 0);
}

// Address range: 0x2c1e - 0x2f97
void function_2c1e(char * a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6) {
    // 0x2c1e
    int32_t v1;
    *(int32_t *)(g2 - 120) = v1;
    *(int32_t *)(g2 - 16) = *(int32_t *)(g2 + 8);
    *(int32_t *)(g2 - 20) = *(int32_t *)(g2 + 12);
    *(int32_t *)(g2 - 24) = *(int32_t *)(g2 + 16);
    *(int32_t *)(g2 - 28) = *(int32_t *)(g2 + 20);
    *(int32_t *)(g2 - 32) = *(int32_t *)(g2 + 24);
    *(int32_t *)(g2 - 36) = *(int32_t *)(g2 + 28);
    int32_t v2 = *(int32_t *)(g2 - 120); // 0x2c46
    int32_t v3 = v2; // eax
    int32_t * v4 = (int32_t *)(v2 + 1010); // 0x2c49_0
    *(int32_t *)(*v4 - 16) = *(int32_t *)(*v4 + 8);
    int32_t * v5 = (int32_t *)(v3 + 1010); // 0x2c5d_0
    *(int32_t *)(*v5 - 20) = *(int32_t *)(*v5 + 12);
    int32_t * v6 = (int32_t *)(v3 + 1010); // 0x2c71_0
    *(int32_t *)(*v6 - 24) = *(int32_t *)(*v6 + 16);
    int32_t * v7 = (int32_t *)(v3 + 1010); // 0x2c85_0
    *(int32_t *)(*v7 - 28) = *(int32_t *)(*v7 + 20);
    int32_t * v8 = (int32_t *)(v3 + 1010); // 0x2c99_0
    *(int32_t *)(*v8 - 32) = *(int32_t *)(*v8 + 24);
    *(int32_t *)(g2 - 44) = *(int32_t *)(g2 - 40) + 562;
    int32_t * v9 = (int32_t *)(g2 - 44); // 0x2cb9_0
    int32_t v10 = *(int32_t *)(*(int32_t *)*v9 + 8); // 0x2cbe
    *(int32_t *)(*(int32_t *)*v9 - 12) = v10;
    *(int32_t *)(g2 - 48) = *(int32_t *)(g2 - 40) + 562;
    int32_t * v11 = (int32_t *)(g2 - 48); // 0x2cd7_0
    int32_t v12 = *(int32_t *)(*(int32_t *)*v11 + 12); // 0x2cdc
    *(int32_t *)(*(int32_t *)*v11 - 16) = v12;
    *(int32_t *)(g2 - 52) = *(int32_t *)(g2 - 40) + 562;
    int32_t * v13 = (int32_t *)(g2 - 52); // 0x2cf5_0
    int32_t v14 = *(int32_t *)(*(int32_t *)*v13 + 16); // 0x2cfa
    *(int32_t *)(*(int32_t *)*v13 - 20) = v14;
    *(int32_t *)(g2 - 56) = *(int32_t *)(g2 - 40) + 562;
    int32_t * v15 = (int32_t *)(g2 - 56); // 0x2d13_0
    int32_t v16 = *(int32_t *)(*(int32_t *)*v15 + 20); // 0x2d18
    *(int32_t *)(*(int32_t *)*v15 - 24) = v16;
    int32_t * v17 = (int32_t *)(v3 + 1010); // 0x2d25_0
    *(int32_t *)(*v17 - 40) = *(int32_t *)(*v17 - 36) + 339;
    *(int32_t *)(g2 - 60) = *(int32_t *)(v3 + 1010) - 40;
    int32_t v18 = *(int32_t *)*(int32_t *)*(int32_t *)(g2 - 60); // 0x2d52
    *(int32_t *)(g2 - 64) = *(int32_t *)(v18 + 8);
    int32_t v19 = *(int32_t *)*(int32_t *)*(int32_t *)(g2 - 60); // 0x2d62
    *(int32_t *)(v19 - 8) = *(int32_t *)(g2 - 64);
    int32_t * v20 = (int32_t *)(v3 + 1010); // 0x2d69_0
    *(int32_t *)(*v20 - 44) = *(int32_t *)(*v20 - 36) + 339;
    *(int32_t *)(g2 - 68) = *(int32_t *)(v3 + 1010) - 44;
    int32_t v21 = *(int32_t *)*(int32_t *)*(int32_t *)(g2 - 68); // 0x2d96
    *(int32_t *)(g2 - 72) = *(int32_t *)(v21 + 12);
    int32_t v22 = *(int32_t *)*(int32_t *)*(int32_t *)(g2 - 68); // 0x2da6
    *(int32_t *)(v22 - 12) = *(int32_t *)(g2 - 72);
    int32_t * v23 = (int32_t *)(v3 + 1010); // 0x2dad_0
    *(int32_t *)(*v23 - 48) = *(int32_t *)(*v23 - 36) + 339;
    *(int32_t *)(g2 - 76) = *(int32_t *)(v3 + 1010) - 48;
    int32_t v24 = *(int32_t *)*(int32_t *)*(int32_t *)(g2 - 76); // 0x2dda
    *(int32_t *)(g2 - 80) = *(int32_t *)(v24 + 16);
    int32_t v25 = *(int32_t *)*(int32_t *)*(int32_t *)(g2 - 76); // 0x2dea
    *(int32_t *)(v25 - 16) = *(int32_t *)(g2 - 80);
    *(int32_t *)(g2 - 84) = *(int32_t *)(*(int32_t *)(g2 - 40) + 562);
    int32_t v26 = *(int32_t *)(g2 - 84); // 0x2dfd
    *(int32_t *)(*(int32_t *)(*(int32_t *)(v26 - 28) + 212) - 4) = 0;
    *(int32_t *)(g2 - 88) = *(int32_t *)(*(int32_t *)(g2 - 40) + 562);
    int32_t v27 = *(int32_t *)(v3 + 1010); // 0x2e20
    *(int32_t *)(g2 - 92) = *(int32_t *)(*(int32_t *)(v27 - 36) + 339);
    int32_t v28 = *(int32_t *)(g2 - 92); // 0x2e3c
    *(int32_t *)(v28 - 24) = *(int32_t *)(*(int32_t *)(g2 - 88) - 28);
    int32_t v29 = *(int32_t *)(v3 + 1010); // 0x2e44
    *(int32_t *)(g2 - 96) = *(int32_t *)(*(int32_t *)(v29 - 36) + 339);
    int32_t v30 = *(int32_t *)(v3 + 1010); // 0x2e60
    *(int32_t *)(v30 - 52) = *(int32_t *)(*(int32_t *)(g2 - 96) - 20);
    int32_t v31 = *(int32_t *)(v3 + 1010); // 0x2e6b
    int32_t v32 = *(int32_t *)(*(int32_t *)(g2 - 40) + 562); // 0x2e79
    *(int32_t *)(v32 - 44) = *(int32_t *)(v31 - 36);
    int32_t v33 = *(int32_t *)(g2 - 40); // 0x2e84
    *(int32_t *)(*(int32_t *)(v3 + 1010) - 64) = v33;
    int32_t v34 = *(int32_t *)(*(int32_t *)(v3 + 1010) - 52); // 0x2e9b
    *(int32_t *)(g2 - 100) = printf((char *)(v34 + 63));
    int32_t v35 = *(int32_t *)(g2 - 120); // 0x2eab
    v3 = v35;
    *(int32_t *)(g2 - 104) = *(int32_t *)(*(int32_t *)(v35 + 1010) - 64);
    int32_t v36 = *(int32_t *)(g2 - 104); // 0x2ebf
    *(int32_t *)(*(int32_t *)(v36 + 562) - 32) = *(int32_t *)(g2 - 100);
    int32_t v37 = *(int32_t *)(*(int32_t *)(g2 - 104) + 562); // 0x2ed0
    int32_t v38 = *(int32_t *)(v3 + 1010); // 0x2edb
    *(int32_t *)(v38 - 56) = *(int32_t *)(v37 - 44);
    int32_t v39 = *(int32_t *)(v3 + 1010); // 0x2ee6
    *(int32_t *)(g2 - 108) = *(int32_t *)(*(int32_t *)(v39 - 56) + 339);
    int32_t v40 = *(int32_t *)(*(int32_t *)(g2 - 104) + 562); // 0x2f05
    *(int32_t *)(v40 - 36) = *(int32_t *)(*(int32_t *)(g2 - 108) - 24);
    int32_t v41 = *(int32_t *)(*(int32_t *)(g2 - 104) + 562); // 0x2f13
    int32_t v42 = *(int32_t *)(v3 + 1010); // 0x2f1e
    *(int32_t *)(v42 - 60) = *(int32_t *)(v41 - 36);
    int32_t v43 = *(int32_t *)(v3 + 1010); // 0x2f29
    *(int32_t *)(g2 - 112) = *(int32_t *)(*(int32_t *)(v43 - 60) + 212);
    int32_t v44 = *(int32_t *)(*(int32_t *)(g2 - 104) + 562); // 0x2f40
    *(int32_t *)(*(int32_t *)(g2 - 112) - 8) = *(int32_t *)(v44 - 32);
    int32_t v45 = *(int32_t *)(*(int32_t *)(g2 - 104) + 562); // 0x2f56
    *(int32_t *)(*(int32_t *)(v45 - 36) + 208) = 0;
    *(int32_t *)(g2 - 116) = *(int32_t *)(*(int32_t *)(g2 - 104) + 562);
    int32_t v46 = *(int32_t *)(*(int32_t *)(v3 + 1010) - 56); // 0x2f88
    *(int32_t *)(v46 + 339) = *(int32_t *)(*(int32_t *)(g2 - 116) - 40);
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: upx (3.91 [lzma])
// Detected functions: 32
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-09-02 21:18:04
