//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>

// ------------------- Function Prototypes --------------------

void function_1f6b(char * a1, int32_t a2, int32_t a3);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // eax
int32_t g2 = 0; // ebp

// ------------------------ Functions -------------------------

// Address range: 0x1f60 - 0x1f6a
int main(int argc, char ** argv) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_1f6b((char *)v2, 0, 0);
    return g1;
}

// Address range: 0x1f6b - 0x1f8c
void function_1f6b(char * a1, int32_t a2, int32_t a3) {
    // 0x1f6b
    *(int32_t *)(g2 - 4) = 0;
    int32_t v1;
    *(int32_t *)(g2 - 8) = printf((char *)(v1 + 63));
    g1 = 0;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: upx (3.91 [lzma])
// Detected functions: 2
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-09-02 21:13:43
