//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>

// ------------------- Function Prototypes --------------------

void _function_1f6b(int32_t a1);
void function_1edd(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7);
void function_1f3c(char * a1, int32_t a2, int32_t a3, int32_t a4);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // eax
int32_t g2 = 0; // ebp

// ------------------------ Functions -------------------------

// Address range: 0x1ed0 - 0x1edc
int main(int argc, char ** argv) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_1edd(v2, 0, 0, 0, 0, 0, 0);
    return g1;
}

// Address range: 0x1edd - 0x1f2f
void function_1edd(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7) {
    int32_t v1 = g2; // 0x1ede
    *(int32_t *)(v1 - 12) = 0;
    *(int32_t *)(g2 - 16) = *(int32_t *)(v1 + 8);
    *(int32_t *)(g2 - 20) = *(int32_t *)(v1 + 12);
    int32_t v2;
    *(int32_t *)(v2 + 307) = v1 - 24;
    int32_t v3 = g2; // 0x1efc
    *(int32_t *)(v3 - 32) = v2;
    *(int32_t *)(g2 - 36) = 0;
    _function_1f6b(*(int32_t *)(v3 - 28));
    g1 = *(int32_t *)(*(int32_t *)(g2 - 32) + 303);
}

// Address range: 0x1f30 - 0x1f3b
void _function_1f6b(int32_t a1) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_1f3c((char *)v2, 0, 0, 0);
}

// Address range: 0x1f3c - 0x1f8c
void function_1f3c(char * a1, int32_t a2, int32_t a3, int32_t a4) {
    *(int32_t *)(g2 - 8) = *(int32_t *)(g2 + 8);
    *(int32_t *)(g2 - 12) = *(int32_t *)(g2 + 12);
    *(int32_t *)(g2 - 16) = *(int32_t *)(g2 + 16);
    int32_t v1;
    *(int32_t *)(*(int32_t *)(v1 + 212) - 4) = 0;
    *(int32_t *)(g2 - 24) = v1;
    int32_t chars_printed = printf((char *)(*(int32_t *)(g2 - 20) + 63));
    int32_t v2 = *(int32_t *)(g2 - 24); // 0x1f6f
    *(int32_t *)(*(int32_t *)(v2 + 212) - 8) = chars_printed;
    *(int32_t *)(v2 + 208) = 0;
    int32_t v3;
    g2 = v3;
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: upx (3.91 [lzma])
// Detected functions: 4
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-09-02 21:14:48
