//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdio.h>

// ------------------- Function Prototypes --------------------

void __function_1f6b(int32_t a1);
void _function_1edd(int32_t a1, int32_t a2);
void _function_1f3c(int32_t a1);
void function_1d0d(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11);
void function_1d8e(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6);
void function_1e6c(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7);
void function_1ebd(char * a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // eax
int32_t g2 = 0; // ebp

// ------------------------ Functions -------------------------

// Address range: 0x1d00 - 0x1d0c
int main(int argc, char ** argv) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_1d0d(v2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
    return g1;
}

// Address range: 0x1d0d - 0x1d7f
void function_1d0d(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9, int32_t a10, int32_t a11) {
    int32_t v1 = g2; // 0x1d0e
    *(int32_t *)(v1 - 12) = 0;
    *(int32_t *)(g2 - 16) = *(int32_t *)(v1 + 8);
    *(int32_t *)(g2 - 20) = *(int32_t *)(v1 + 12);
    int32_t v2;
    *(int32_t *)(v2 + 771) = v1 - 24;
    int32_t v3 = g2; // 0x1d2c
    *(int32_t *)(v3 - 32) = v2;
    *(int32_t *)(g2 - 36) = 0;
    _function_1edd(*(int32_t *)(v3 - 28), 0);
    g1 = *(int32_t *)(*(int32_t *)(g2 - 32) + 767);
}

// Address range: 0x1d80 - 0x1d8d
void _function_1edd(int32_t a1, int32_t a2) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_1d8e(v2, 0, 0, 0, 0, 0);
}

// Address range: 0x1d8e - 0x1e5f
void function_1d8e(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6) {
    int32_t v1 = g2; // 0x1d8f
    int32_t v2;
    *(int32_t *)(v1 - 56) = v2;
    int32_t v3 = g2; // 0x1da1
    *(int32_t *)(v3 - 60) = *(int32_t *)(v3 + 12);
    int32_t v4 = g2; // 0x1da7
    *(int32_t *)(v4 - 16) = *(int32_t *)(v4 + 8);
    int32_t v5 = g2; // 0x1dad
    *(int32_t *)(v5 - 20) = *(int32_t *)(v5 - 60);
    *(int32_t *)(g2 - 24) = *(int32_t *)(v1 + 16);
    *(int32_t *)(g2 - 28) = *(int32_t *)(v1 + 20);
    *(int32_t *)(g2 - 32) = *(int32_t *)(v1 + 24);
    *(int32_t *)(g2 - 36) = *(int32_t *)(v1 + 28);
    *(int32_t *)(g2 - 40) = *(int32_t *)(v1 + 32);
    int32_t v6 = g2; // 0x1dc2
    int32_t v7 = *(int32_t *)(v6 - 56); // 0x1dc2
    *(int32_t *)(v6 - 44) = *(int32_t *)(v7 + 642);
    *(int32_t *)(*(int32_t *)(g2 - 44) - 12) = 0;
    int32_t v8 = *(int32_t *)(*(int32_t *)(g2 - 44) + 8); // 0x1ddd
    *(int32_t *)(*(int32_t *)(v7 + 642) - 16) = v8;
    int32_t v9 = *(int32_t *)(*(int32_t *)(g2 - 44) + 12); // 0x1dee
    *(int32_t *)(*(int32_t *)(v7 + 642) - 20) = v9;
    int32_t v10 = g2; // 0x1dfc
    int32_t v11 = *(int32_t *)(v10 - 48); // 0x1e02
    *(int32_t *)(v11 + 307) = *(int32_t *)(v10 - 44) - 24;
    *(int32_t *)(g2 - 52) = *(int32_t *)(v7 + 642);
    int32_t v12 = g2; // 0x1e14
    *(int32_t *)(*(int32_t *)(v12 - 52) - 32) = *(int32_t *)(v12 - 48);
    *(int32_t *)(*(int32_t *)(v7 + 642) - 36) = 0;
    __function_1f6b(*(int32_t *)(*(int32_t *)(g2 - 52) - 28));
    int32_t v13 = *(int32_t *)(g2 - 56); // 0x1e3e
    int32_t v14 = *(int32_t *)(*(int32_t *)(*(int32_t *)(v13 + 642) - 32) + 303); // 0x1e4c
    *(int32_t *)(v13 + 638) = v14;
    int32_t v15;
    g2 = v15;
}

// Address range: 0x1e60 - 0x1e6b
void __function_1f6b(int32_t a1) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_1e6c(v2, 0, 0, 0, 0, 0, 0);
}

// Address range: 0x1e6c - 0x1eaf
void function_1e6c(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7) {
    int32_t v1 = g2; // 0x1e6d
    *(int32_t *)(v1 - 8) = *(int32_t *)(v1 + 8);
    int32_t v2;
    *(int32_t *)(v2 + 420) = v1 - 12;
    int32_t v3 = g2; // 0x1e7e
    *(int32_t *)(v3 - 20) = 0;
    _function_1f3c(*(int32_t *)(v3 - 16));
    int32_t v4;
    g2 = v4;
}

// Address range: 0x1eb0 - 0x1ebc
void _function_1f3c(int32_t a1) {
    int32_t v1;
    g2 = &v1;
    int32_t v2;
    function_1ebd((char *)v2, 0, 0, 0, 0);
}

// Address range: 0x1ebd - 0x1f8c
void function_1ebd(char * a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5) {
    *(int32_t *)(g2 - 12) = *(int32_t *)(g2 + 8);
    *(int32_t *)(g2 - 16) = *(int32_t *)(g2 + 12);
    *(int32_t *)(g2 - 20) = *(int32_t *)(g2 + 16);
    *(int32_t *)(g2 - 24) = *(int32_t *)(g2 + 20);
    int32_t v1;
    int32_t * v2 = (int32_t *)(v1 + 339); // 0x1ed6_0
    *(int32_t *)(*v2 - 8) = *(int32_t *)(*v2 + 8);
    int32_t * v3 = (int32_t *)(v1 + 339); // 0x1eea_0
    *(int32_t *)(*v3 - 12) = *(int32_t *)(*v3 + 12);
    int32_t * v4 = (int32_t *)(v1 + 339); // 0x1efe_0
    *(int32_t *)(*v4 - 16) = *(int32_t *)(*v4 + 16);
    *(int32_t *)(*(int32_t *)(*(int32_t *)(g2 - 28) + 212) - 4) = 0;
    *(int32_t *)(*(int32_t *)(v1 + 339) - 24) = *(int32_t *)(g2 - 28);
    int32_t v5 = *(int32_t *)(*(int32_t *)(v1 + 339) - 20); // 0x1f3b
    *(int32_t *)(g2 - 44) = v1;
    *(int32_t *)(g2 - 32) = printf((char *)(v5 + 63));
    int32_t v6 = *(int32_t *)(g2 - 44); // 0x1f4e
    *(int32_t *)(g2 - 36) = *(int32_t *)(*(int32_t *)(v6 + 339) - 24);
    int32_t v7 = *(int32_t *)(g2 - 36); // 0x1f62
    *(int32_t *)(*(int32_t *)(v7 + 212) - 8) = *(int32_t *)(g2 - 32);
    *(int32_t *)(*(int32_t *)(g2 - 36) + 208) = 0;
    *(int32_t *)(v6 + 339) = *(int32_t *)(g2 - 40);
}

// --------------- Dynamically Linked Functions ---------------

// int printf(const char * restrict format, ...);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: upx (3.91 [lzma])
// Detected functions: 8
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-09-02 21:15:53
